version: '3.8'

services:
  person-db-postgres:
    container_name: "population-data-center-api-postgres"
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: deoGratias
      POSTGRES_USER: postgres
      POSTGRES_DB: person-db
    volumes:
      - ./data-postgres:/var/lib/postgresql/data # postgres data mounting point
      - ./sql:/root/sql # sql for export/import

  #spring-starter:
  #  container_name: spring-starter
  #  image: spring-starter:0.0.1
  #  ports:
  #    - "8080:8080"
  #  environment:
  #    DATABASE_USERNAME: kotlin
  #    DATABASE_PASSWORD: kotlin
  #    DATABASE_URL: jdbc:postgresql://spring-starter-api-postgres:5432/restful-api
