version: '3.5'

services:
  spring-starter:
    container_name: spring-starter
    image: spring-starter:0.0.1
    ports:
      - "8080:8080"
    environment:
      DATABASE_USERNAME: kotlin
      DATABASE_PASSWORD: kotlin
      DATABASE_URL: jdbc:postgresql://spring-starter-api-postgres:5432/restful-api
  spring-starter-postgres:
    container_name: "spring-starter-api-postgres"
    image: postgres:12-apline
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: kotlin
      POSTGRES_USER: kotlin
      POSTGRES_DB: person-db